//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Issues) DeepCopyInto(out *Issues) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Issues.
func (in *Issues) DeepCopy() *Issues {
	if in == nil {
		return nil
	}
	out := new(Issues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Issues) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuesList) DeepCopyInto(out *IssuesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Issues, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuesList.
func (in *IssuesList) DeepCopy() *IssuesList {
	if in == nil {
		return nil
	}
	out := new(IssuesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IssuesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuesObservation) DeepCopyInto(out *IssuesObservation) {
	*out = *in
	if in.DetectApps != nil {
		in, out := &in.DetectApps, &out.DetectApps
		*out = new(bool)
		**out = **in
	}
	if in.DetectInfra != nil {
		in, out := &in.DetectInfra, &out.DetectInfra
		*out = new(bool)
		**out = **in
	}
	if in.DetectTxn != nil {
		in, out := &in.DetectTxn, &out.DetectTxn
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuesObservation.
func (in *IssuesObservation) DeepCopy() *IssuesObservation {
	if in == nil {
		return nil
	}
	out := new(IssuesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuesParameters) DeepCopyInto(out *IssuesParameters) {
	*out = *in
	if in.DetectApps != nil {
		in, out := &in.DetectApps, &out.DetectApps
		*out = new(bool)
		**out = **in
	}
	if in.DetectInfra != nil {
		in, out := &in.DetectInfra, &out.DetectInfra
		*out = new(bool)
		**out = **in
	}
	if in.DetectTxn != nil {
		in, out := &in.DetectTxn, &out.DetectTxn
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuesParameters.
func (in *IssuesParameters) DeepCopy() *IssuesParameters {
	if in == nil {
		return nil
	}
	out := new(IssuesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuesSpec) DeepCopyInto(out *IssuesSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuesSpec.
func (in *IssuesSpec) DeepCopy() *IssuesSpec {
	if in == nil {
		return nil
	}
	out := new(IssuesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuesStatus) DeepCopyInto(out *IssuesStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuesStatus.
func (in *IssuesStatus) DeepCopy() *IssuesStatus {
	if in == nil {
		return nil
	}
	out := new(IssuesStatus)
	in.DeepCopyInto(out)
	return out
}
