/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type IssuesObservation struct {

	// Detect frequent issues within applications, enabled (`true`) or disabled (`false`)
	DetectApps *bool `json:"detectApps,omitempty" tf:"detect_apps,omitempty"`

	// Detect frequent issues within infrastructure, enabled (`true`) or disabled (`false`)
	DetectInfra *bool `json:"detectInfra,omitempty" tf:"detect_infra,omitempty"`

	// Detect frequent issues within transactions and services, enabled (`true`) or disabled (`false`)
	DetectTxn *bool `json:"detectTxn,omitempty" tf:"detect_txn,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type IssuesParameters struct {

	// Detect frequent issues within applications, enabled (`true`) or disabled (`false`)
	// +kubebuilder:validation:Optional
	DetectApps *bool `json:"detectApps,omitempty" tf:"detect_apps,omitempty"`

	// Detect frequent issues within infrastructure, enabled (`true`) or disabled (`false`)
	// +kubebuilder:validation:Optional
	DetectInfra *bool `json:"detectInfra,omitempty" tf:"detect_infra,omitempty"`

	// Detect frequent issues within transactions and services, enabled (`true`) or disabled (`false`)
	// +kubebuilder:validation:Optional
	DetectTxn *bool `json:"detectTxn,omitempty" tf:"detect_txn,omitempty"`
}

// IssuesSpec defines the desired state of Issues
type IssuesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IssuesParameters `json:"forProvider"`
}

// IssuesStatus defines the observed state of Issues.
type IssuesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IssuesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Issues is the Schema for the Issuess API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type Issues struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.detectApps)",message="detectApps is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.detectInfra)",message="detectInfra is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.detectTxn)",message="detectTxn is a required parameter"
	Spec   IssuesSpec   `json:"spec"`
	Status IssuesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IssuesList contains a list of Issuess
type IssuesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Issues `json:"items"`
}

// Repository type metadata.
var (
	Issues_Kind             = "Issues"
	Issues_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Issues_Kind}.String()
	Issues_KindAPIVersion   = Issues_Kind + "." + CRDGroupVersion.String()
	Issues_GroupVersionKind = CRDGroupVersion.WithKind(Issues_Kind)
)

func init() {
	SchemeBuilder.Register(&Issues{}, &IssuesList{})
}
