//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueDetection) DeepCopyInto(out *FrequentIssueDetection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueDetection.
func (in *FrequentIssueDetection) DeepCopy() *FrequentIssueDetection {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueDetection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FrequentIssueDetection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueDetectionList) DeepCopyInto(out *FrequentIssueDetectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FrequentIssueDetection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueDetectionList.
func (in *FrequentIssueDetectionList) DeepCopy() *FrequentIssueDetectionList {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueDetectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FrequentIssueDetectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueDetectionObservation) DeepCopyInto(out *FrequentIssueDetectionObservation) {
	*out = *in
	if in.DetectApps != nil {
		in, out := &in.DetectApps, &out.DetectApps
		*out = new(bool)
		**out = **in
	}
	if in.DetectInfra != nil {
		in, out := &in.DetectInfra, &out.DetectInfra
		*out = new(bool)
		**out = **in
	}
	if in.DetectTxn != nil {
		in, out := &in.DetectTxn, &out.DetectTxn
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueDetectionObservation.
func (in *FrequentIssueDetectionObservation) DeepCopy() *FrequentIssueDetectionObservation {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueDetectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueDetectionParameters) DeepCopyInto(out *FrequentIssueDetectionParameters) {
	*out = *in
	if in.DetectApps != nil {
		in, out := &in.DetectApps, &out.DetectApps
		*out = new(bool)
		**out = **in
	}
	if in.DetectInfra != nil {
		in, out := &in.DetectInfra, &out.DetectInfra
		*out = new(bool)
		**out = **in
	}
	if in.DetectTxn != nil {
		in, out := &in.DetectTxn, &out.DetectTxn
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueDetectionParameters.
func (in *FrequentIssueDetectionParameters) DeepCopy() *FrequentIssueDetectionParameters {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueDetectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueDetectionSpec) DeepCopyInto(out *FrequentIssueDetectionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueDetectionSpec.
func (in *FrequentIssueDetectionSpec) DeepCopy() *FrequentIssueDetectionSpec {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueDetectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueDetectionStatus) DeepCopyInto(out *FrequentIssueDetectionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueDetectionStatus.
func (in *FrequentIssueDetectionStatus) DeepCopy() *FrequentIssueDetectionStatus {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueDetectionStatus)
	in.DeepCopyInto(out)
	return out
}
