//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssue) DeepCopyInto(out *FrequentIssue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssue.
func (in *FrequentIssue) DeepCopy() *FrequentIssue {
	if in == nil {
		return nil
	}
	out := new(FrequentIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FrequentIssue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueList) DeepCopyInto(out *FrequentIssueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FrequentIssue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueList.
func (in *FrequentIssueList) DeepCopy() *FrequentIssueList {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FrequentIssueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueObservation) DeepCopyInto(out *FrequentIssueObservation) {
	*out = *in
	if in.DetectApps != nil {
		in, out := &in.DetectApps, &out.DetectApps
		*out = new(bool)
		**out = **in
	}
	if in.DetectInfra != nil {
		in, out := &in.DetectInfra, &out.DetectInfra
		*out = new(bool)
		**out = **in
	}
	if in.DetectTxn != nil {
		in, out := &in.DetectTxn, &out.DetectTxn
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueObservation.
func (in *FrequentIssueObservation) DeepCopy() *FrequentIssueObservation {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueParameters) DeepCopyInto(out *FrequentIssueParameters) {
	*out = *in
	if in.DetectApps != nil {
		in, out := &in.DetectApps, &out.DetectApps
		*out = new(bool)
		**out = **in
	}
	if in.DetectInfra != nil {
		in, out := &in.DetectInfra, &out.DetectInfra
		*out = new(bool)
		**out = **in
	}
	if in.DetectTxn != nil {
		in, out := &in.DetectTxn, &out.DetectTxn
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueParameters.
func (in *FrequentIssueParameters) DeepCopy() *FrequentIssueParameters {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueSpec) DeepCopyInto(out *FrequentIssueSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueSpec.
func (in *FrequentIssueSpec) DeepCopy() *FrequentIssueSpec {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrequentIssueStatus) DeepCopyInto(out *FrequentIssueStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrequentIssueStatus.
func (in *FrequentIssueStatus) DeepCopy() *FrequentIssueStatus {
	if in == nil {
		return nil
	}
	out := new(FrequentIssueStatus)
	in.DeepCopyInto(out)
	return out
}
